const dbConfig = require("../config/config-db");
const mongoose = require("mongoose");
mongoose.Promise = global.Promise;
const db = {};
db.mongoose = mongoose
db.url = dbConfig.url;
db.produits = require ("./produits")
db.contacts = require ("./contacts")
module.exports = db;